"""音頻配置設定"""

# 音頻設備設定
AUDIO_DEVICE_INDEX = None  # 自動偵測 PD100X
AUDIO_SAMPLE_RATE = 44100
AUDIO_CHANNELS = 1  # 單聲道

# 錄製設定
MAX_RECORDING_DURATION = 60  # 秒
RECORDING_FORMAT = 'int16'
RECORDING_DIRECTORY = "recordings"

# 設備偵測
PD100X_DEVICE_NAMES = [
    "PD100X",
    "PODCAST MICROPHONE",
    "USB AUDIO",
    "MICROPHONE",
]